### ISSUE TITLE
Task with path 'testDebugUnitTest' not found in project ':app'.

### ISSUE THREAD

**Issue by Kolyall** [CaffeinatedAndroid/demo-merge-android-coverage#1]
Error:
Could not determine the dependencies of task ':app:jacocoCombinedTestReports'.
> Task with path 'testDebugUnitTest' not found in project ':app'.

My app.gradle:
```
android {

flavorDimensions "dev"

buildTypes {
        release {
            minifyEnabled true
            debuggable false
          
        }
        debugMinify { /*debug build with minify enabled */
            versionNameSuffix "-debugMinify"
            minifyEnabled true
            debuggable true
         
        }
        debug {
            testCoverageEnabled true
         
            minifyEnabled false
            debuggable true
        }
    }

  productFlavors {
        prd {
        
        }
     
        stg { /*stage*/
        
            applicationId "${androidApplicationId}.stg"
        
        }
        dev { /*develop*/
     
            applicationId "${androidApplicationId}.dev"
      
        }
      
    }
```

**Comment by ChristopherBull** [comment]
Hi Kolyall,

Could you provide your complete *.gradle files (both the project/app one and the module level one) and perhaps some details about which version of Android Studio and Gradle you are using. Possibly a link to a GitHub project/commit where you are experiencing this. I was expecting to see some dependencies for JaCoCo, for example. I am also not sure why `testDebugUnitTest` cannot be found by `:app`, as that is part of Android/Gradle.

Examples of what works in this project snippet can be seen here:

- In the [project-level `build.gradle`](build.gradle) file
- and the [module-level `build.gradle`](app/build.gradle) file (e.g., `/app/build.gradle`).
